### ISSUE TITLE
Has anyone successfully implemented Swipeout with this library?

### ISSUE THREAD

**Issue by GShotwell** [deanmcpherson/react-native-sortable-listview#58]
I'm trying to set up a list which allows the user to sort and also allows them to swipe-to-delete. Is this possible?

**Comment by chetstone** [comment]
I tried to do this using SwipeRow from react-native-swipe-list-view. It didn’t work very well.
I had to separate the swipe action from the sort action using a different page. And it’s still not working well. The swipe action might be fixable according to this comment. The sorting page does not work well in my app even by itself, partly because I have a long list and I am embedding this component in a ScrollView.

This is all on Android. I have looked at several similar components and they all seem to have similar problems.

For iOS I highly recommend react-native-tableview. It works very, very well. Too bad Android does not seem to have a similar native component that can be wrapped from RN.

**Comment by chetstone** [comment]
@GShotwell I've tried using SwipeRow again with my code from PR #61 and it seems to work pretty well.

**Comment by vTrip** [comment]
@chetstone can you confirm the functionality you have working i.e. swipe out and sortable list....either or.

success on both iOS and Android ?

**Comment by chetstone** [comment]
As I mentioned above, I did try it with my code from PR #61 on android. It worked, but I changed my app design and am not currently using it. 

I did not try iOS. As I also mentioned above, I use a different component on iOS.

**Comment by vTrip** [comment]
I can confirm working functionality on iOS device in simulator 10.2

**Comment by chetstone** [comment]
@vTrip thanks for confirming on iOS.

**Comment by vTrip** [comment]
@chetstone running into issues on actual device where touch event is not accessible.

Works fine in simulator as I stated above previously, just not on actual device.

Cannot see any errors occurring. Any thoughts ?

**Comment by vTrip** [comment]
@chetstone 

I just updated to the latest version after revisiting this and discovered that on 0.2.2 the reverse actually happens. 

Sortable functionality is disabled and the swipeout action works.

This occurs on both real device and simulator.

I might look into your implementation above of using a different component on iOS.
